routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Web Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('admin', 'HomeController@login')->name('admin.login');
Route::get('admin/dashboard/', 'HomeController@index')->name('admin.dashboard');
Route::get('admin/article-request/', 'ArticleRequestController@index')->name('admin.article_request');
Route::get('admin/article-request/edit/{id}', 'ArticleRequestController@edit')->name('admin.article_request.edit');
Route::post('admin/article-request/{id}', 'ArticleRequestController@update')->name('admin.article_request.update');

Route::get('admin/published-article/', 'ManageArticleController@published')->name('admin.published_article');
Route::get('admin/rejected-article/', 'ManageArticleController@rejected')->name('admin.rejected_article');
Route::get('admin/suspends-article/', 'ManageArticleController@suspend')->name('admin.suspend_article');

Route::get('admin/member/', 'ListDataController@member')->name('admin.member');

Route::get('admin/intern-author/', 'ListDataController@intern_author')->name('admin.intern_author');
Route::get('admin/intern-author/add', 'InternAuthorController@add')->name('admin.intern_author_add');
Route::post('admin/intern-author', 'InternAuthorController@store')->name('admin.intern_author.store');

Route::get('admin/extern-author/', 'ListDataController@extern_author')->name('admin.extern_author');

Route::get('admin/author-request', 'AuthorRequestController@index')->name('admin.author_request');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//
//Route::get('/', function () {
//    return view('welcome');
//});

	Auth::routes();

//	Route::get('/home', 'HomeController@index')->name('home');

	Route::get('/', 'Front\HomeController@index');

	Route::get('market-news/all', 'Front\MarketNewsController@index');
	Route::get('market-news/indonesian-economy', 'Front\MarketNewsController@indonesian_economy');
	Route::get('market-news/international-economy', 'Front\MarketNewsController@international_economy');
	Route::get('market-news/company-announcement', 'Front\MarketNewsController@company_announcement');

	Route::get('market-outlook', 'Front\MarketOutlookController@index');

	Route::get('stock-ideas/buy-ideas', 'Front\StockIdeasController@buy_ideas');
	Route::get('stock-ideas/sell-ideas', 'Front\StockIdeasController@sell_ideas');
	Route::get('stock-ideas/sectors', 'Front\StockIdeasController@sectors');

	Route::get('discount/regional', 'Front\DiscountController@regional');
	Route::get('discount/newest', 'Front\DiscountController@newest');
	Route::get('discount/likes', 'Front\DiscountController@likes');

	Route::get('IR-presentation/latest', 'Front\IRPresentationController@latest');
	Route::get('IR-presentation/search-within-ir', 'Front\IRPresentationController@search_within_ir');

	Route::get('broker/latest', 'Front\BrokerReportController@latest');
	Route::get('broker/search-with-in-broker', 'Front\BrokerReportController@search_with');

	Route::get('funds/index-funds', 'Front\FundsController@index_funds');
	Route::get('funds/active-funds', 'Front\FundsController@active_funds');

	Route::get('pro', 'Front\ProController@index');

	Route::get('marketplace', 'Front\MarketPlaceController@index');
	Route::get('marketplace/information/{id}', 'Front\MarketPlaceController@information')->name('marketplace.information');
	Route::get('marketplace/getpayment/{id}', 'Front\MarketPlaceController@getPayment');
	Route::get('marketplace/confirm-payment/{id}', 'Front\MarketPlaceController@payments');
	Route::get('marketplace/subscribe', 'Front\MarketPlaceController@subscribe')->name('marketplace.subscribe');
	Route::get('marketplace/subscribe/wait/{id}', 'Front\MarketPlaceController@subscribe_message')->name('marketplace.subscribe.wait');
	Route::get('marketplace/pick-article/{id}', 'Front\MarketPlaceController@pick_article');
	Route::get('marketplace/limit-pick-article/{id}/{ids}', 'Front\MarketPlaceController@limit_pick_article');

	Route::any('member/mail/register', 'Member\RegisterController@mail_register')->name('member.mail.register');
	Route::any('member/register/{token?}', 'Member\RegisterController@member_register')->name('member.register');
	Route::get('member/register/welcome/{token?}', 'Member\RegisterController@welcome')->name('member.welcome');

	Route::get('account/home', 'Member\HomeController@home')->name('member.home');
	Route::get('account/feed', 'Member\HomeController@feed');
	Route::get('account/profile', 'Member\ProfileController@comments');
	Route::get('account/profile/followers', 'Member\ProfileController@followers');
	Route::get('account/profile/following', 'Member\ProfileController@following');
	Route::get('account/profile/comments', 'Member\ProfileController@comments');
	Route::get('account/profile/stocktalks', 'Member\ProfileController@stocktalks');
	Route::get('account/profile/edit/{id}', 'Member\ProfileController@edit');
	Route::get('account/latest', 'Member\HomeController@latest');
	Route::get('account/articles', 'Member\HomeController@articles');
	Route::get('account/paid-articles', 'Member\HomeController@paid_articles');
	Route::get('account/news', 'Member\HomeController@news');
	Route::get('account/data', 'Member\HomeController@data');
	Route::get('account/alert', 'Member\HomeController@alert');
	Route::get('account/stock-talks', 'Member\HomeController@stock_talks');
	Route::get('account/became-author', 'Member\HomeController@became_author');
	Route::any('account/interest/article/{slug}', 'Member\HomeController@article_detail')->name('account.interest.article.detail');
	Route::any('account/paid/article/{slug}', 'Member\HomeController@article_detail_paid')->name('account.paid.article.detail');
	Route::get('account/manage-article', 'Member\ArticleController@manage_article');

	Route::any('account/sign-in', 'Author\DashboardController@login')->name('author.login');
	Route::post('logout', 'Author\LogoutController@logout')->name('user.logout');

	Route::group(['middleware'=>'author'], function() {
		Route::get('authors/', 'Author\DashboardController@index')->name('author.home');
		Route::any('authors/write-article', 'Author\ArticleController@write_article');
		Route::get('authors/manage-article', 'Author\ArticleController@manage_article')->name('author.manage.article');
		Route::get('authors/manage-article/pending', 'Author\ArticleController@pending_article');
		Route::get('authors/manage-article/published', 'Author\ArticleController@published_article');
		Route::get('authors/manage-article/blog-post', 'Author\ArticleController@blogpost_article');
		Route::any('authors/mail-box', 'Author\MailboxController@index');
		Route::any('authors/profile', 'Author\ProfileController@index');
		Route::any('authors/manage-profile/interest', 'Author\ProfileController@ShowInterest')->name('author.profileinterest');
		Route::any('authors/manage-profile/personal-detail', 'Author\ProfileController@ShowPersonalDetail')->name('author.profilepersonal');

		Route::get('authors/manage-article/all', 'Author\ArticleController@article_all');
		Route::get('authors/manage-article/market-news', 'Author\ArticleController@article_marketNews');
		Route::get('authors/manage-article/market-outlook', 'Author\ArticleController@article_marketOutlook');
		Route::get('authors/manage-article/stockideas', 'Author\ArticleController@article_StockIdeas');
		Route::get('authors/manage-article/IR-presentation', 'Author\ArticleController@article_irPresentation');
		Route::get('authors/manage-article/broker-report', 'Author\ArticleController@article_brokerReport');
		Route::get('authors/manage-article/funds', 'Author\ArticleController@article_funds');
		Route::get('authors/manage-article-comments', 'Author\ArticleCommentController@index');
		Route::get('authors/article/{slug}', 'Author\ArticleController@article_detail')->name('author.article.detail');
		Route::any('authors/article/{slug}/edit', 'Author\ArticleController@article_edit')->name('author.article.edit');

		Route::post('upload_image', 'Author\ArticleController@upload_image')->name('article.upload.image');

	});

	Route::any('authors/mail/register', 'Author\RegisterController@mail_register')->name('author.mail.register');
	Route::any('authors/register/{token?}', 'Author\RegisterController@author_register')->name('author.register');
	Route::get('authors/register/welcome/{token?}', 'Author\RegisterController@welcome')->name('author.welcome');

	Route::get('authors/profile/{id}', 'Author\ProfileController@profiles')->name('author.profile');

	Route::post('/strEditorUpdate', 'Admin\ArticleRequestController@write_article');


	Route::any('article/{slug}', 'Front\HomeController@article_detail')->name('article.detail');

	Route::get('decrypts', function(){

		$encrypt = "eyJpdiI6IjdmWEdZOHpBUlNobE1KTGtRWlJIaEE9PSIsInZhbHVlIjoiRlBGZk54a1RycWpjb3ZZOG9HVktMQT09IiwibWFjIjoiZDUwOTA5YzIyYmM5YjM0MWEzZTcyMzAxYTVmYjNhZThlYjMxYWRmMjE3MmJjMzI5YzI4ZWEyMWM2M2M4MmU3MSJ9";

		dd(decrypt($encrypt));
	});

	Route::get('encrypt', function(){
		dd(encrypt(24));
	});

	Route::get('timestring', function(){
		$dt = Carbon\Carbon::now();

		dd($dt->format('c'));
	});

app/Http/Controllers/Front/IRPresentationController.php
<?php

namespace App\Http\Controllers\Front;

use App\Article;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class IRPresentationController extends Controller
{
	public function latest()
	{
		$article = Article::with('author')->withCount('article_comment')->where('article_type', '6A')->orderBy('id', 'desc')->get();
		return view('layouts.front.pages.ir_presentation.latest', compact('article'));
	}

	public function search_within_ir()
	{
		$article = Article::with('author')->withCount('article_comment')->where('article_type', '6A')->orderBy('id', 'desc')->get();
		return view('layouts.front.pages.ir_presentation.search_within_ir', compact('article'));
	}
}

resources/views/layouts/front/pages/ir_presentation/latest.blade.php
@extends('layouts.front.index')

@section('style')
    <link rel="shortcut icon" href="{{ asset('web/img/logo.png') }}" type="image/x-icon"/>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300,400,400italic,700' rel='stylesheet' type='text/css'>
    <link rel='stylesheet' id='twitter-bootstrap-css' href='{{ asset('web/css/bootstrap.min.css') }}' type='text/css' media='all'/>
    <link rel='stylesheet' id='fontello-css' href='{{ asset('web/css/fontello.css') }}' type='text/css' media='all'/>
    <link rel='stylesheet' id='fontello-css' href='{{ asset('web/css/custom.css') }}' type='text/css' media='all'/>
    <link rel="stylesheet" type="text/css" href="{{ asset('web/css/table.css') }}" media="screen"/>
    <link rel='stylesheet' id='prettyphoto-css-css' href='{{ asset('web/js/prettyphoto/css/prettyPhoto.css') }}' type='text/css' media='all'/>
    <link rel='stylesheet' id='animation-css' href='{{ asset('web/css/animation.css') }}' type='text/css' media='all'/>
    <link rel='stylesheet' id='flexSlider-css' href='{{ asset('web/css/flexslider.css') }}' type='text/css' media='all'/>
    <link rel='stylesheet' id='perfectscrollbar-css' href='{{ asset('web/css/perfect-scrollbar-0.4.10.min.css') }}' type='text/css' media='all'/>
    <link rel='stylesheet' id='jquery-validity-css' href='{{ asset('web/css/jquery.validity.css') }}' type='text/css' media='all'/>
    <link rel='stylesheet' id='jquery-ui-css' href='{{ asset('web/css/jquery-ui.min.css') }}' type='text/css' media='all'/>
    <link rel='stylesheet' id='style-css' href='{{ asset('web/css/style.css') }}' type='text/css' media='all'/>
    <link rel='stylesheet' id='mobilenav-css' href='{{ asset('web/css/mobilenav.css') }}' type='text/css' media="screen and (max-width: 838px)"/>
    <link rel="stylesheet" type="text/css" href="{{ asset('web/css/style.revslider.css') }}" media="screen"/>
    <link rel="stylesheet" type="text/css" href="{{ asset('web/js/rs-plugin/css/settings.css') }}" media="screen"/>

    <!-- jQuery -->
    <script src="{{ asset('web/js/jquery-1.11.1.min.js') }}"></script>
    <!-- Google Maps -->
    <script type='text/javascript' src='http://maps.google.com/maps/api/js?sensor=false&#038;ver=4.0'></script>
    <!--[if lt IE 9]>
    <script>
        document.createElement("header");
        document.createElement("nav");
        document.createElement("section");
        document.createElement("article");
        document.createElement("aside");
        document.createElement("footer");
        document.createElement("hgroup");

    </script>
    <![endif]-->
    <!--[if lt IE 9]>
    <script src="{{ asset('web/js/html5.js') }}"></script>
    <![endif]-->
    <!--[if lt IE 7]>
    <script src="{{ asset('web/js/icomoon.js') }}"></script>
    <![endif]-->
    <!--[if lt IE 9]>
    <link href="{{ asset('css/ie.css') }}" rel="stylesheet">
    <![endif]-->
    <!--[if lt IE 9]>
    <script src="{{ asset('js/jquery.placeholder.js') }}"></script>
    <script src="{{ asset('js/script_ie.js') }}"></script>
    <![endif]-->
@endsection

@section('content')
    <section id="main-content">
        <div class="row contents">
            <section class="main-content col-lg-9 col-md-8 col-sm-8 small-padding">
                <div class="row">
                    <div class="col-md-12">
                        <div class="post blog-post blog-post-classic col-lg-12 col-md-12 col-sm-12">
                            <div class="blog-post-list">
                                <div class="blog-post-content">
                                    <div class="post-content">
                                        <ul class="post-meta">
                                            <li>
                                                <h4>Latest Investor Relation Presentation</h4>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="post blog-post blog-post-classic col-lg-12 col-md-12 col-sm-12">
                            @foreach ($article as $b)
                                <div class="blog-post-list ">
                                    <div class="blog-post-content">
                                        <div class="post-content">
                                            <h4><a href="{{ route('article.detail', $b->slug) }}" title="{{$b->title}}">{{$b->title}}</a></h4>
                                            <div class="font-black">
                                              {!!substr($b->description, 0, 300).' ...'!!}
                                            </div>
                                            <a class="read-more big" href="{{ route('article.detail', $b->slug) }}">Learn more</a>
                                            <ul class="post-meta">
                                                <li><a href="#">Author : {{$b->author->name}}</a></li>
                                                <li>{{$b->article_comment_count}} comments</li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            @endforeach
                        </div>
                    </div>
                    <div class="clearfix">
                        <p>&nbsp;</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 ">
                        <ul class="pagination pull-right">
                            <li><a href="#">1</a></li>
                            <li><a href="#">2</a></li>
                            <li><a href="#">3</a></li>
                            <li><a href="#">4</a></li>
                            <li><a href="#">5</a></li>
                        </ul>
                    </div>
                </div>
            </section>
            <aside class="col-lg-3 col-md-4 col-sm-4 small-padding">
                &nbsp;
            </aside>
        </div>
    </section>
@endsection

@section('script')
    <script type='text/javascript' src='{{ asset('web/js/bootstrap.min.js') }}'></script>
    <script type='text/javascript' src='{{ asset('web/js/jquery-ui.min.js') }}'></script>
    <script type='text/javascript' src='{{ asset('web/js/jquery.easing.1.3.js') }}'></script>
    <script type='text/javascript' src='{{ asset('web/js/jquery.mousewheel.min.js') }}'></script>
    <script type='text/javascript' src='{{ asset('web/js/SmoothScroll.min.js') }}'></script>
    <script type='text/javascript' src='{{ asset('web/js/prettyphoto/js/jquery.prettyPhoto.js') }}'></script>
    <script type='text/javascript' src='{{ asset('web/js/modernizr.js') }}'></script>
    <script type='text/javascript' src='{{ asset('web/js/wow.min.js') }}'></script>
    <script type='text/javascript' src='{{ asset('web/js/jquery.sharre.min.js') }}'></script>
    <script type='text/javascript' src='{{ asset('web/js/jquery.flexslider-min.js') }}'></script>
    <script type='text/javascript' src='{{ asset('web/js/jquery.knob.js') }}'></script>
    <script type='text/javascript' src='{{ asset('web/js/jquery.mixitup.min.js') }}'></script>
    <script type='text/javascript' src='{{ asset('web/js/masonry.min.js?ver=3.1.2') }}'></script>
    <script type='text/javascript' src='{{ asset('web/js/jquery.masonry.min.js?ver=3.1.2') }}'></script>
    <script type='text/javascript' src='{{ asset('web/js/jquery.fitvids.js') }}'></script>
    <script type='text/javascript' src='{{ asset('web/js/perfect-scrollbar-0.4.10.with-mousewheel.min.js') }}'></script>
    <script type='text/javascript' src='{{ asset('web/js/jquery.nouislider.min.js') }}'></script>
    <script type='text/javascript' src='{{ asset('web/js/jquery.validity.min.js') }}'></script>
    <script type='text/javascript' src='{{ asset('web/js/tweetie.min.js') }}'></script>
    <script type='text/javascript' src='{{ asset('web/js/script.js') }}'></script>
    <script type='text/javascript' src='{{ asset('web/js/rs-plugin/js/jquery.themepunch.enablelog.js') }}'></script>
    <script type='text/javascript' src='{{ asset('web/js/rs-plugin/js/jquery.themepunch.revolution.js') }}'></script>
    <script type='text/javascript' src='{{ asset('web/js/rs-plugin/js/jquery.themepunch.revolution.min.js') }}'></script>
    <script type='text/javascript' src='{{ asset('web/js/rs-plugin/js/jquery.themepunch.tools.min.js') }}'></script>
    <script type="text/javascript">
        jQuery(document).ready(function() {


            jQuery('.tp-banner').show().revolution(
                    {
                        dottedOverlay:"none",
                        delay:16000,
                        startwidth:1170,
                        startheight:700,
                        hideThumbs:200,
                        thumbWidth:100,
                        thumbHeight:50,
                        thumbAmount:5,
                        navigationType:"bullet",
                        navigationArrows:"solo",
                        navigationStyle:"preview2",
                        touchenabled:"on",
                        onHoverStop:"on",
                        swipe_velocity: 0.7,
                        swipe_min_touches: 1,
                        swipe_max_touches: 1,
                        drag_block_vertical: false,
                        parallax:"mouse",
                        parallaxBgFreeze:"on",
                        parallaxLevels:[7,4,3,2,5,4,3,2,1,0],
                        keyboardNavigation:"off",
                        navigationHAlign:"center",
                        navigationVAlign:"bottom",
                        navigationHOffset:0,
                        navigationVOffset:20,
                        soloArrowLeftHalign:"left",
                        soloArrowLeftValign:"center",
                        soloArrowLeftHOffset:20,
                        soloArrowLeftVOffset:0,
                        soloArrowRightHalign:"right",
                        soloArrowRightValign:"center",
                        soloArrowRightHOffset:20,
                        soloArrowRightVOffset:0,
                        shadow:0,
                        fullWidth:"on",
                        fullScreen:"off",
                        spinner:"spinner4",
                        stopLoop:"off",
                        stopAfterLoops:-1,
                        stopAtSlide:-1,
                        shuffle:"off",
                        autoHeight:"off",
                        forceFullWidth:"off",
                        hideThumbsOnMobile:"off",
                        hideNavDelayOnMobile:1500,
                        hideBulletsOnMobile:"off",
                        hideArrowsOnMobile:"off",
                        hideThumbsUnderResolution:0,
                        hideSliderAtLimit:0,
                        hideCaptionAtLimit:0,
                        hideAllCaptionAtLilmit:0,
                        startWithSlide:0,
                        videoJsPath:"rs-plugin/videojs/",
                        fullScreenOffsetContainer: ""
                    });
        }); //ready
    </script>
@endsection